name: turb-sound
channels:
  - conda-forge
  - defaults
dependencies:
  - h5py=3.7.0
  - ipython=8.8.0
  - jupyter=1.0.0
  - matplotlib=3.6.3
  - numpy=1.24.1
  - pandas=1.5.3
  - python=3.10.8
  - scipy=1.10.0
  - tensorflow=2.11.0
